version: '3.7'
services:
    backend:
        environment: 
            FLASK_ENV: development
        build: backend/.
        ports:
            - "5000:5000"
        volumes:
            - .:/code
        init: true
        depends_on:
            - redis
    redis:
        image: redis
    frontend:
        build: frontend/dragonhack-sinergise/.
        ports:
            - "8080:8080"
        volumes:
            - .:/code
        init: true
        depends_on: 
            - backend
