version: '3.7'
services:
    web:
        build: .
        ports:
            - "5000:5000"
        volumes:
            - .:/code
        init: true
        depends_on:
            - redis
    redis:
        image: redis